# Generated by Django 5.1.7 on 2025-04-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
