# Generated by Django 5.1.7 on 2025-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_coupon_max_discount_alter_coupon_min_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
