# Generated by Django 5.1.7 on 2025-04-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 14, 40, 24, 319860)),
        ),
    ]
