# Generated by Django 5.1.7 on 2025-04-02 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_alter_coupon_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 9, 34, 15, 290545)),
        ),
    ]
