# Generated by Django 5.1.7 on 2025-03-27 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_price_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 19, 7, 28, 207773)),
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, to='products.material'),
        ),
    ]
