# Generated by Django 5.1.7 on 2025-03-27 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_start_date_remove_product_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 21, 12, 9, 195316)),
        ),
    ]
