# Generated by Django 5.1.7 on 2025-03-28 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_price_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 8, 28, 7, 784171)),
        ),
    ]
