# Generated by Django 5.1.7 on 2025-03-28 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_brand_alter_price_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdimension',
            name='weigh',
        ),
        migrations.AddField(
            model_name='itemdimension',
            name='weights',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemdimension',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemdimension',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemdimension',
            name='width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 18, 17, 36, 999576)),
        ),
    ]
