# Generated by Django 5.1.7 on 2025-03-31 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_itemdimension_weigh_itemdimension_weights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 31, 10, 15, 27, 559015)),
        ),
    ]
