# Generated by Django 5.1.7 on 2025-04-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_price_start_date_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='imported_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 1, 14, 40, 24, 303819)),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 14, 40, 24, 319860)),
        ),
    ]
