# Generated by Django 5.1.7 on 2025-04-02 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_batch_imported_at_alter_price_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='imported_at',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 9, 34, 15, 287545)),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 9, 34, 15, 288546)),
        ),
    ]
