# Generated by Django 5.1.7 on 2025-04-01 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 1, 14, 40, 24, 319860)),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 1, 14, 40, 24, 319860)),
        ),
    ]
